pluginManagement {
    repositories {
        gradlePluginPortal()
        google()             // <-- This is the one we were missing!
        mavenCentral()
    }
}

includeBuild 'build-logic'
includeBuild 'fun.with'
rootProject.name = 'mel'

include ':auth'
include ':authfx'
include ':blog'
include ':contacts'
include ':contactsfx'
include ':filedump'
include ':filedumpfx'
include ':filesync'
include ':filesyncfx'
include ':fxbundle'
include ':icons'
include 'json'
include 'konsole'
include 'lok'
include ':miniserver'
include ':serialize'
include ':serverparts'
include ':sql'
include ':testtools'


include 'android'
