// build-logic/build.gradle
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Use your versions from the TOML file
        def versionKotlinGradle = libs.versions.kotlin.gradle.get().toString()
        def versionAndroidBuild = libs.versions.androidGradlePluginVersion.get()
//        def gradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${libs.versions.kotlin.asProvider().get()}"
//        def buildPlugin = "com.android.tools.build:gradle:${libs.versions.androidGradlePluginVersion.get()}"
        println("VERSION kotlin gradle plugin ${versionKotlinGradle}")
        println("VERSION android tools ${versionAndroidBuild}")

        classpath "com.android.tools.build:gradle:${versionAndroidBuild}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${versionKotlinGradle}"
//        classpath "com.android.tools.build:gradle:${buildPlugin}"
//        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${gradlePlugin}"
    }
}

plugins {
    id 'groovy-gradle-plugin'
}


dependencies {
    implementation libs.kotlin.gradle.plugin
    implementation "com.android.tools.build:gradle-api:${libs.versions.androidGradlePluginVersion.get()}"
//    implementation libs.android.gradle.plugin
    implementation libs.openjfx.plugin.artifact
}


// This part is unchanged
gradlePlugin {
    plugins {
        javaLibrary {
            id = 'mel-java-library'
            implementationClass = 'unused'
        }
        androidApplication {
            id = 'mel-android-application'
            implementationClass = 'unused'
        }
        kotlinApplication {
            id = 'mel-kotlin-application'
            implementationClass = 'unused'
        }
        kotlinJvmLibrary {
            id = 'mel-kotlin-jvm-library'
            implementationClass = 'unused'
        }
        javafxLibrary {
            id = 'mel-javafx-library'
            implementationClass = 'unused'
        }
        javafxApplication {
            id = 'mel-javafx-application'
            implementationClass = 'unused'
        }
    }
}