plugins {
    id 'mel-kotlin-jvm-library'
}


dependencies {
    api 'fun.with:fun.with'
    api project(':konsole')
    api project(':sql')
    implementation libs.kotlin.coroutines
    implementation libs.bouncycastle.jdk18.pkix
    implementation libs.bouncycastle.jdk18.prov
    implementation libs.sqlite.jdbc
    api libs.jdeferred
//    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
//    implementation 'org.bouncycastle:bcprov-jdk18on:1.82'
//    implementation 'org.xerial:sqlite-jdbc:3.50.3.0'

    testImplementation project(path: ':testtools')
    testImplementation project(path: ':sql')
    testImplementation project(path: ':serialize', configuration: 'serializeTestOutput')


//    api rootProject.dep_k_std
//    api rootProject.dep_k_cor
//    api rootProject.dep_jdeferred
//    api rootProject.dep_bc_prov
//    api rootProject.dep_bc_pkix
}