// konsole/build.gradle

// 1. Apply our custom Java library template
plugins {
    id 'mel-java-library'
}

// 2. Add dependencies specific to 'konsole'
dependencies {
    // We use 'api' here because 'konsole' DEPENDS ON 'lok'
    // This means any project that depends on 'konsole'
    // will AUTOMATICALLY get 'lok' as well.
    api project(':lok')
}