plugins{
    id 'mel-kotlin-jvm-library'
}

sourceSets {
    main {
//        resources {
//            srcDir "${project(':auth').projectDir}/src/main/resources"
//        }
    }
}
dependencies {
    api project(':auth')
    implementation libs.kotlin.stdlib
    implementation libs.kotlin.coroutines
    testImplementation project(":auth")
//    implementation rootProject.dep_k_std
//    testImplementation rootProject.dep_junit4
//    testImplementation project(":auth")
}