plugins{
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}

sourceSets {
    main {
//        resources {
//            srcDir "${project(':auth').projectDir}/src/main/resources"
//        }
    }
}
dependencies {
    api project(':auth')
    implementation rootProject.dep_k_std
    testImplementation rootProject.dep_junit4
    testImplementation project(":auth")
}



//compileJava {
//    sourceCompatibility = '21'
//    targetCompatibility = '21'
//}

//compileKotlin {
//    kotlinOptions {
//        jvmTarget = "21"
//    }
//}
//compileTestKotlin {
//    kotlinOptions {
//        jvmTarget = "21"
//    }
//}