plugins{
    id 'mel-kotlin-jvm-library'
}

configurations{
    filesyncTestOutput
}
sourceSets {
    main {
        resources {
//            srcDir "${project(':auth').projectDir}/src/main/resources"
        }
    }
}
dependencies {
    filesyncTestOutput sourceSets.test.output
    api project(':auth')
    implementation libs.kotlin.coroutines
}
